# Exploración del Dataset

In [5]:
import numpy as np
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Cargamos los datos de la tabla de galaxias centrales
data_centrales = pl.read_csv('data/tracks_centrales_snap28.csv')

# Cargamos los datos de las fusines
data_fusiones = pl.read_csv('data/historial_merger_centrales_snap28.csv')

In [12]:
mask = (pl.col('Lm') > 1.1) & (pl.col('Lm') < 2.5) & (pl.col('Snapshot') > 11)

data_fusiones.filter(mask).sort('GalaxyID')

shape: (3_017, 3)
┌──────────┬──────────┬──────────┐
│ GalaxyID ┆ Snapshot ┆ Lm       │
│ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 3397222  ┆ 12       ┆ 1.130452 │
│ 8358440  ┆ 17       ┆ 1.158701 │
│ 8358440  ┆ 22       ┆ 1.563961 │
│ 8358440  ┆ 23       ┆ 1.182579 │
│ 8358440  ┆ 26       ┆ 1.338338 │
│ …        ┆ …        ┆ …        │
│ 21730535 ┆ 16       ┆ 1.150915 │
│ 21730535 ┆ 22       ┆ 1.118266 │
│ 21924775 ┆ 19       ┆ 1.225271 │
│ 21986361 ┆ 17       ┆ 1.460567 │
│ 21986361 ┆ 22       ┆ 1.21606  │
└──────────┴──────────┴──────────┘

In [ ]:
mask_snap = (pl.col('Snapshot') == 16) & (pl.col('Lm') < 2.5) & (pl.col('Lm') > 1.25)

data_fusiones.filter(mask_snap).group_by('GalaxyID').agg(pl.count('Lm').alias('Count')).sort('GalaxyID')

shape: (76, 2)
┌──────────┬─────┐
│ GalaxyID ┆ Lm  │
│ ---      ┆ --- │
│ i64      ┆ u32 │
╞══════════╪═════╡
│ 8787254  ┆ 1   │
│ 8824645  ┆ 1   │
│ 8827411  ┆ 1   │
│ 8883148  ┆ 1   │
│ 8898960  ┆ 1   │
│ …        ┆ …   │
│ 18475201 ┆ 1   │
│ 19462908 ┆ 1   │
│ 19891777 ┆ 1   │
│ 20259284 ┆ 1   │
│ 20809088 ┆ 1   │
└──────────┴─────┘